config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get '/auth/:provider/callback', to: 'users/omniauth_callbacks#facebook'
  get '/auth/failure', to: redirect('/')

  # You can have the root of your site routed with "root"
  root 'generals#homepage'

  resource :generals
  resources :competitions do
    member do
      get 'load_competition'
    end
  end
  resources :protocol_wl_competitions do
    member do
      get 'update'
    end
  end
  resources :sports do
    member do
      get 'panel'
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/sport.rb
class Sport < ActiveRecord::Base

  has_many :athlete_categories

  validates :name, presence: true, uniqueness: true
  validates :uid, presence: true, uniqueness: true

  before_create :do_before_create

  def to_param
    uid
  end

  def do_before_create
    make_uid
  end

  def make_uid
    self.uid = self.name.parameterize
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  before_action :set_sport, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @sports = Sport.all
    respond_with(@sports)
  end

  def show
    respond_with(@sport)
  end

  def new
    @sport = Sport.new
    respond_with(@sport)
  end

  def edit
  end

  def create
    @sport = Sport.new(sport_params)
    @sport.save
    respond_with(@sport)
  end

  def update
    @sport.update(sport_params)
    respond_with(@sport)
  end

  def destroy
    @sport.destroy
    respond_with(@sport)
  end

  def panel
    @competition = Competition.new
    @protocol = ProtocolWlCompetition.new
    @athletic_categories = {}
    AthleteCategory.all.each{|c| @athletic_categories[c.name] = c.id}
    respond_with(@sport)
  end

  private
    def set_sport
      @sport = Sport.find_by_uid(params[:id])
    end

    def sport_params
      params.require(:sport).permit(:name, :uid, :description)
    end
end

app/helpers/sports_helper.rb
module SportsHelper
end

app/views/sports/_form.html.haml
= form_for @sport do |f|
  - if @sport.errors.any?
    #error_explanation
      %h2= "#{pluralize(@sport.errors.count, "error")} prohibited this sport from being saved:"
      %ul
        - @sport.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :uid
    = f.text_field :uid
  .field
    = f.label :description
    = f.text_area :description
  .actions
    = f.submit 'Save'

app/views/sports/edit.html.haml
%h1 Editing sport

= render 'form'

= link_to 'Show', @sport
\|
= link_to 'Back', sports_path

app/views/sports/index.html.haml
%h1 Listing sports

%table
  %thead
    %tr
      %th Name
      %th Uid
      %th Description
      %th
      %th
      %th
      
  %tbody
    - @sports.each do |sport|
      %tr
        %td= sport.name
        %td= sport.uid
        %td= sport.description
        %td= link_to 'Show', sport
        %td= link_to 'Edit', edit_sport_path(sport)
        %td= link_to 'Destroy', sport, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Sport', new_sport_path

app/views/sports/new.html.haml
%h1 New sport

= render 'form'

= link_to 'Back', sports_path

app/views/sports/panel.html.haml
-content_for :head_image do
  =image_tag 'sport-icons/weightlifting.png'

.row
  .col-lg-12
    %h2.slide Змагання
    .competitions-container
      = render 'sports/weightlifting/competitions'
.row
  .col-lg-12
    %h2.slide Додати учасника
    .sportsman-form.hide
      = render 'sports/weightlifting/add_sportsman'
    %h2.slide Протокол зважування
    .protocol-weighing-container
      -# 'sports/weightlifting/protocol_weighing'
.row
  .col-lg-12
    %h2.slide Протокол змагань
    .protocol-competitions-container
      -# 'sports/weightlifting/protocol_competitions'

app/views/sports/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @sport.name
%p
  %b Uid:
  = @sport.uid
%p
  %b Description:
  = @sport.description

= link_to 'Edit', edit_sport_path(@sport)
\|
= link_to 'Back', sports_path